fr_hollen:
    resource: "@FRHollenBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: @AppBundle/Controller/
    type:     annotation

#User
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"