# default routes
fr_hollen_homepage:
    path: /home
    defaults: { _controller: FRHollenBundle:Default:index }

fr_hollen_planning:
    path: /planning/{stage}/{day}
    defaults: { _controller: FRHollenBundle:Default:planning, stage: ALL, day: ALL }
    requirements:
        stage: ([A-Za-z0-9\-])*
        day: (\d{2})|(ALL)

# Users
fr_hollen_list_users:
    path: /user/list
    defaults: { _controller: FRHollenBundle:Admin:listUsers }

fr_hollen_grant_user:
    path: /user/grant/{id}
    defaults: { _controller: FRHollenBundle:Admin:grantUser }
    requirements:
        id: \d*

fr_hollen_ungrant_user:
    path: /user/ungrant/{id}
    defaults: { _controller: FRHollenBundle:Admin:ungrantUser }
    requirements:
        id: \d*

fr_hollen_remove_user:
    path: /user/remove/{id}
    defaults: { _controller: FRHollenBundle:Admin:removeUser }
    requirements:
        id: \d*

# Rockbands
fr_hollen_list_rockbands:
    path: /rockband/list
    defaults: { _controller: FRHollenBundle:Admin:listRockbands }

fr_hollen_add_rockband:
    path: /rockband/add
    defaults: { _controller: FRHollenBundle:Admin:addRockband }

fr_hollen_update_rockband:
    path: /rockband/update/{id}
    defaults: { _controller: FRHollenBundle:Admin:updateRockband }
    requirements:
        id: \d*

fr_hollen_remove_rockband:
    path: /rockband/remove/{id}
    defaults: { _controller: FRHollenBundle:Admin:removeRockband }
    requirements:
        id: \d*

# Concerts
fr_hollen_list_concerts:
    path: /concert/list
    defaults: { _controller: FRHollenBundle:Admin:listConcerts }

fr_hollen_add_concert:
    path: /concert/add
    defaults: { _controller: FRHollenBundle:Admin:addConcert }

fr_hollen_update_concert:
    path: /concert/update/{id}
    defaults: { _controller: FRHollenBundle:Admin:updateConcert }
    requirements:
        id: \d*

fr_hollen_remove_concert:
    path: /concert/remove/{id}
    defaults: { _controller: FRHollenBundle:Admin:removeConcert }
    requirements:
        id: \d*

# 