# default routes
fr_hollen_homepage:
    path: /home
    defaults: { _controller: FRHollenBundle:Default:index }

fr_hollen_edit_user:
    path: /edit/user
    defaults: { _controller: FRHollenBundle:Default:editUser }

fr_hollen_planning:
    path: /planning/stage/{stage_id}/begin/{begin_int}/end/{end_int}/genre/{genre_id}
    defaults: { _controller: FRHollenBundle:Default:planning, stage_id: ALL, begin_int: NO_BEGIN, end_int: NO_END, genre_id: ANY }
    requirements:
        stage_id:  (\d+)|(ALL)
        begin_int: (\d+)|(NO_BEGIN)
        end_int:   (\d+)|(NO_END)
        genre_id:  (\d+)|(ANY)

fr_hollen_add_order:
    path: /order/add/{id}
    defaults: { _controller: FRHollenBundle:Default:addOrder }
    requirements:
        id: \d+

fr_hollen_remove_order:
    path: /order/remove/{id}
    defaults: { _controller: FRHollenBundle:Default:removeOrder }
    requirements:
        id: \d+

# Users
fr_hollen_list_users:
    path: /user/list
    defaults: { _controller: FRHollenBundle:Admin:listUsers }

fr_hollen_grant_user:
    path: /user/grant/{id}
    defaults: { _controller: FRHollenBundle:Admin:grantUser }
    requirements:
        id: \d+

fr_hollen_ungrant_user:
    path: /user/ungrant/{id}
    defaults: { _controller: FRHollenBundle:Admin:ungrantUser }
    requirements:
        id: \d+

fr_hollen_remove_user:
    path: /user/remove/{id}
    defaults: { _controller: FRHollenBundle:Admin:removeUser }
    requirements:
        id: \d+

# Genres
fr_hollen_list_genres:
    path: /genre/list
    defaults: { _controller: FRHollenBundle:Admin:listGenres }

fr_hollen_add_genre:
    path: /genre/add/{id}
    defaults: { _controller: FRHollenBundle:Admin:addGenre, id: null }
    requirements:
        id: \d+

fr_hollen_remove_genre:
    path: /genre/remove/{id}
    defaults: { _controller: FRHollenBundle:Admin:removeGenre }
    requirements:
        id: \d+

# Rockbands
fr_hollen_list_rockbands:
    path: /rockband/list
    defaults: { _controller: FRHollenBundle:Admin:listRockbands }

fr_hollen_add_rockband:
    path: /rockband/add/{id}
    defaults: { _controller: FRHollenBundle:Admin:addRockband, id: null }
    requirements:
        id: \d+

fr_hollen_remove_rockband:
    path: /rockband/remove/{id}
    defaults: { _controller: FRHollenBundle:Admin:removeRockband }
    requirements:
        id: \d+

# Stages
fr_hollen_list_stages:
    path: /stage/list
    defaults: { _controller: FRHollenBundle:Admin:listStages }

fr_hollen_add_stage:
    path: /stage/add/{id}
    defaults: { _controller: FRHollenBundle:Admin:addStage, id: null }
    requirements:
        id: \d+

fr_hollen_remove_stage:
    path: /stage/remove/{id}
    defaults: { _controller: FRHollenBundle:Admin:removeStage }
    requirements:
        id: \d+

# Concerts
fr_hollen_list_concerts:
    path: /concert/list
    defaults: { _controller: FRHollenBundle:Admin:listConcerts }

fr_hollen_add_concert:
    path: /concert/add/{id}
    defaults: { _controller: FRHollenBundle:Admin:addConcert, id: null }
    requirements:
        id: \d+

fr_hollen_remove_concert:
    path: /concert/remove/{id}
    defaults: { _controller: FRHollenBundle:Admin:removeConcert }
    requirements:
        id: \d+

# Other
fr_hollen_other:
    path: /spaghetti
    defaults: { _controller: FRHollenBundle:Default:other }

fr_hollen_html2pdf:
    path: /html2pdf
    defaults: { _controller: FRHollenBundle:Default:html2pdf }