fr_hollen_homepage:
    path:     /home
    defaults: { _controller: FRHollenBundle:Default:index }

fr_hollen_planning:
    path:     /planning
    defaults: { _controller: FRHollenBundle:Default:planning }
